### ISSUE TITLE
Parent window scrolls to top

### ISSUE THREAD

**Issue by zeroseisdesign** [fancyapps/fancyBox#1003]
The parent window scrolls to top when you click on a link fancybox if the body has the css height attribute to 100% instead of auto. 

This is the project make with bootstrap with cover fullscreen: http://desarrollo.campustraining.es/app/cemp/landings/mcd/

Anybody knows how to solve this issue?
 Thanks

**Comment by TJung1968** [comment]
Hi,

I had the same issue and fixed it with by commenting out a line in jquery.fancybox.css:
```css
.fancybox-lock {
    /* overflow: hidden !important; */
    width: auto;
}
```

I found this solution here:
http://stackoverflow.com/questions/13547007/fancybox2-fancybox-causes-page-to-to-jump-to-the-top/17458177#17458177

Hope this helps on your site, too!
Kind Regards!
