### ISSUE TITLE
ios 9 Safari css overlay bug

### ISSUE THREAD

**Issue by splintercode** [fancyapps/fancyBox#1068]
It looks like the overlay ignores z-index on ios9 causing the image to be under the overlay obscuring it. The demo site on ios 9 has this issue. 

A temp fix is using adding a translateZ property. Not an ideal solution though. 

``` css
.facybox-opened {
  z-index: 8030;
  transform: translateZ(100px); /* added */
}
```

**Comment by cvalya** [comment]
I see this bug on iPhone 5 and iPhone 5c with iOS 9. iPhone 6 with iOS 9 work fine.

**Comment by devmod** [comment]
+1!

**Comment by ckweb** [comment]
This temp fix worked for me, too, but the class name is "fancybox-opened":
```css
.fancybox-opened {
    transform: translateZ(100px); 
}
```
