### ISSUE TITLE
flicker issue happened in mobile

### ISSUE THREAD

**Issue by jackyon** [fancyapps/fancybox#1265]
hi, 

i have one lightbox that using inline content with input form, everything is perfect but I got flicker issue while switching to different inputs in iphone 5 & iphone 6, I think this issue is the container that using position: fixed, after i changed it to absolute and I found the flicker issue gone, but the lightbox position goes to top.

is there any solution for this weird thing? plz suggest, thx!

**Comment by fancyapps** [comment]
Hi,  I`m now trying to find a nice workaround to this issue.

**Comment by fancyapps** [comment]
The easiest fix I found is to use this CSS snippet:

```CSS
html,body{
    -webkit-overflow-scrolling : touch !important;
    overflow: auto !important;
    height: 100% !important;
}
```
I tried various workarounds, but looks like position change from fixed to absolute will be needed.
