### ISSUE TITLE
Locking the background so it doesn't scroll

### ISSUE THREAD

**Issue by mlazkani** [fancyapps/fancybox#1364]
Hello, is there a way to lock the background so it doesn't scroll when launching fancybox. Currently, if I'm outside the overlay I'm able to scroll the background but on your homepage examples, the background doesn't scroll.

see: http://take.ms/vXCCi

**Comment by fancyapps** [comment]
Hi,

This is enabled by default and actually, there is no option to disable this.

If your page scrolls, then probably there is come CSS conflict on your page. Seeing your page would help to determine the cause.

**Comment by Poky85** [comment]
@fancyapps I can disable background scroll lock with simple CSS:

```css
body.fancybox-active {
	overflow: scroll;
}
/* Required to enable scroll on iOS. But in core.js you refer 
to iOS bug with inputs inside fixed elements. So removing position: fixed on body 
can break something? */
body.fancybox-iosfix {
	position: static;
}
body.compensate-for-scrollbar {
	margin-right: 0;
}
```

This seems ok in various devices. But I'm worried that it can break modal in iOS (see comment above). Further because Fancybox doesn't support this internally, there is problem with loosing scroll position on Fancybox close (because of https://github.com/fancyapps/fancybox/blob/master/src/js/core.js#L2607).

Do you plan to add this feature or there are some good reasons why you didn't implemented it?
