### ISSUE TITLE
Color of fancybox3

### ISSUE THREAD

**Issue by Thor111** [fancyapps/fancybox#1370]
Hi, where i can make the color of the fancybox3 something darker? TY.

**Comment by fancyapps** [comment]
Hi, You mean background? You can change color/opacity using CSS:

```CSS
.fancybox-container--ready .fancybox-bg {
    opacity: 1;
    background: #000;
}
```

**Comment by mlazkani** [comment]
Is it possible to set a different background color/opacity for different html webpage overlays:

Main Page:

Launch Page 1 ~> page1.html (opens with a white background overlay)
Launch page 2 ~> page2.html (opens with a black background overlay)

Thx

**Comment by fancyapps** [comment]
@mlazkani You could, for example, use "baseClass" option to set different class name to container and then set background color depending on it.

**Comment by fancyapps** [comment]
FYI, v3.1 has been released. This is how you can change color and/or opacity:

```CSS
.fancybox-bg {
    background: #888;
}

.fancybox-is-open .fancybox-bg {
    opacity: 1;
}
```

**Comment by i7eo** [comment]
in fancybox v3.5, jquery v1.12

overlayOpacity & overlayColor doesn't effected.

```
<a href="#inline2" id="test">test</a>

<div id="inline2" style="display:none">
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	</p>
</div>
```

```
$("#test").fancybox({
    'transitionIn': 'none',
    'transitionOut': 'none',
    'width': 1200,
    'height': 300,
    'overlayColor': '#AFADAD',
    'overlayOpacity': '.6',
    'showCloseButton': false,
});
```

**Comment by fancyapps** [comment]
For v3, you have to use CSS, see previous answer for code sample. Demo - https://codepen.io/anon/pen/rRwRym

**Comment by bilogic** [comment]
> Launch Page 1 ~> page1.html (opens with a white background overlay)
> Launch page 2 ~> page2.html (opens with a black background overlay)

I think many of us are using templating engine, i.e. blade/twig.
Is it possible to use CSS and apply a different style for different iframe links?

**Comment by fancyapps** [comment]
@bilogic Of` course, simply use `baseClass` option to set custom class name for container, example:


```HTML
<p>
  <a href="https://codepen.io/about/" data-fancybox data-options='{"type" : "iframe", "baseClass" : "fancybox-white"}'>
    Example #1
  </a>

  <br />
  
  <a href="https://codepen.io/pro/teams/" data-fancybox data-options='{"type" : "iframe", "baseClass" : "fancybox-black"}'>
    Example #2
  </a>
</p>
```

```CSS
.fancybox-white .fancybox-bg {
  background: white;
}

.fancybox-black .fancybox-bg {
  background: black;
}
```

Demo - https://codepen.io/anon/pen/MMPabj?editors=1100
