### ISSUE TITLE
Better CSS for Buttons

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1475]
I'm not entirely sure why you continue to use fixed pixel values for the Fancybox UI buttons, for example:

```css
.fancybox-button--close::before, .fancybox-button--close::after {
  top: calc(50% - 1px);
  left: calc(50% - 8px);
}

.fancybox-button--left::after,
.fancybox-button--right::after {
  top: 18px;
}

.fancybox-button--left::after {
  left: 20px;
}

.fancybox-button--right::after {
  right: 20px;
}
```

You're already using the transform property for some things, so there's no compatibility issue in also using it for positioning. I believe this is far better than the above:

```css
.fancybox-button::before,
.fancybox-button::after,
.fancybox-button--left::after,
.fancybox-button--right::after {
	top: 50%; right: auto; bottom: auto;
	left:50%;
	-webkit-transform: translate(-50%,-50%);
	    -ms-transform: translate(-50%,-50%);
	        transform: translate(-50%,-50%);
}

.fancybox-button--close::before {
  -webkit-transform: translate(-50%,-50%) rotate(45deg);
      -ms-transform: translate(-50%,-50%) rotate(45deg);
          transform: translate(-50%,-50%) rotate(45deg);
}

.fancybox-button--close::after {
  -webkit-transform: translate(-50%,-50%) rotate(-45deg);
      -ms-transform: translate(-50%,-50%) rotate(-45deg);
          transform: translate(-50%,-50%) rotate(-45deg); 
}
```

And this allows users to easily customize button sizes, without having to rewrite the rules for positioning. For example, it's now easy to do this:

```css
.fancybox-button {
	line-height: 52px;
	width: 52px; height: 52px;
}
```

... and the icons remain perfectly centered.

**Comment by mjcampagna** [comment]
This is what I've got for arrows:

```css
.fancybox-arrow,
.fancybox-arrow::after {
	margin: 0;
	top: 50%; left: 0;
	-webkit-transform: translate(0,-50%);
	    -ms-transform: translate(0,-50%);
	        transform: translate(0,-50%);
}

.fancybox-arrow--right {
	left: auto; right: 0;
}

.fancybox-arrow--left {
	-webkit-transform: translate(0,-50%) scaleX(-1);
	    -ms-transform: translate(0,-50%) scaleX(-1);
	        transform: translate(0,-50%) scaleX(-1);	
}
```
