### ISSUE TITLE
iOS - Resize to full screen not working on iFrame

### ISSUE THREAD

**Issue by bcordis** [fancyapps/fancybox#1493]
Links are not resizing to full screen on the press of expansion button. Have tested on Safari and Google Chrome browser.

Also not allowing for resizing from CSS being set.

https://www.nfsda.org/resources/sermons/sermon/409-mara-is-not-far-from-elim/1.html

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not understand - 
1) what do you mean by that. iOS Safari does not support fullscreen API. 
2) What does this mean - "Also not allowing for resizing from CSS being set" ? - what, where, why?

btw, I noticed that you need to set both to make it align correctly:

```CSS
#video_container {
    display: inline-block;
    vertical-align: middle;
}
```
