### ISSUE TITLE
how resize thumbnails from js or tag?

### ISSUE THREAD

**Issue by protoror** [fancyapps/fancybox#1511]
it possible for any data-fancybox group create different thumbnail dimension use js or better if tag parameters line data-thumvnail?

**Comment by fancyapps** [comment]
Hi,

Thumbnail dimensions are controlled using CSS. If you want to customize based on some condition, then you could, for example, use `baseClass` option to add custom class to the layout and then customize based on that, for example:

```CSS
.myCustomBaseCass .fancybox-thumbs > ul > li {
    width: 105px;
    height: 75px;
}
```

You probably would want to update layout, too.
