### ISSUE TITLE
Multiple video dimensions on same page?

### ISSUE THREAD

**Issue by MoxieCat** [fancyapps/fancybox#1530]
I have pages that use both 4:3 and 16:9 videos. I'd like to set the 4:3 videos to open as 640px wide and the 16:9 videos at 854px wide. The ".fancybox-slide--video .fancybox-content" style works great to set a a size for a video to open at - BUT can apparently only be set once per page.

I have tried using a descendant selector, both applied to the video's containing DIV and as a class on the link itself, but data-fancybox apparently ignores other classes when calling the video dimensions style.

Am I missing something? How can I specify multiple video dimensions on the same page?

PS - Otherwise, thanks for a great new version of Fancybox! I love it!

**Comment by fancyapps** [comment]
Hi,

Therefore there is a handy `slideClass` option, you can add custom CSS to any link. For example:


```HTML
<a data-fancybox href="https://www.youtube.com/watch?v=_sI_Ps7JSEk" data-options='{"slideClass":"video__4-3"}'>
    YouTube video
</a>

<a data-fancybox href="https://vimeo.com/191947042" data-options='{"slideClass":"video__16-9"}'>
    Vimeo video
</a>
```

and then set any dimensions you want:

```CSS
.video__4-3 .fancybox-content {
  width: 640px;
  height: 480px;
}

.video__16-9 .fancybox-content {
  width: 854px;
  height: 480px;
}
```

Demo - https://codepen.io/anon/pen/dRLjXv?editors=1100
