### ISSUE TITLE
Slideshow controls too small on mobile

### ISSUE THREAD

**Issue by ffolkes** [fancyapps/fancybox#1566]
Are there any plans to add css to make the slideshow mode interface bigger when viewed on a mobile device? The controls are very small.

**Comment by fancyapps** [comment]
Hi,

Do not be afraid to customize the interface. That is why JS and CSS are separated, so you can easily customize the design.

For example, you can simply scale the toolbar:

```CSS
.fancybox-toolbar {
    transform: scale(2,2);
}
```
