### ISSUE TITLE
Select text in caption

### ISSUE THREAD

**Issue by Stadly** [fancyapps/fancybox#1604]
It is not possible to select the text in the caption. Even when touch is disabled.

**Comment by fancyapps** [comment]
So, I assume you would like to make it selectable? 😄  You can do it easily using CSS:

```CSS
.fancybox-caption-wrap {
    pointer-events: all;
}
```
