### ISSUE TITLE
Is it possible to make the video fit to view?

### ISSUE THREAD

**Issue by nsynsynsy** [fancyapps/fancybox#1730]
When we using viewport like 768x1024, ipad. The black background of the video is too long on screen, is it possible to make the video auto fit the height of the original video size? fit to view option?

**Comment by fancyapps** [comment]
Hi,

What do you mean by "The black background of the video is too long on screen"?

Dimensions of html content are controlled by CSS width/height/max-width/max-height rules and iframes fit inside the view-port by default:

```CSS
.fancybox-slide--iframe .fancybox-content {
    width: 80%;
    height: 80%;
    max-width: calc(100% - 100px);
    max-height: calc(100% - 88px);
}
```
