### ISSUE TITLE
Loader CSS Tweak

### ISSUE THREAD

**Issue by mjcampagna** [fancyapps/fancybox#1762]
An incredibly minor thing, but something I noticed.

````css
.fancybox-slide > .fancybox-loading {
  border: 6px solid rgba(100, 100, 100, 0.4);
  border-top: 6px solid rgba(255, 255, 255, 0.6);
  border-radius: 100%;
  height: 50px;
  width: 50px;
  -webkit-animation: fancybox-rotate .8s infinite linear;
  animation: fancybox-rotate .8s infinite linear;
  background: transparent;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -30px;
  margin-left: -30px;
  z-index: 99999; }
````

Given the positioning, and the width and height values of 50px, I think you probably meant the margin-top/left values to be -25px, not -30px.
