### ISSUE TITLE
Watermark with text: bad effect opening slide.

### ISSUE THREAD

**Issue by ieraora** [fancyapps/fancybox#1834]
Hallo Jānis, in this example https://codepen.io/ieraora/pen/qxmNde I added a Watermark.
For you it's a way to view text only when slide is open, and than avoid bad effect during open the slide?
Same problem I have when it closing.

Thank You.

**Comment by fancyapps** [comment]
Hi,

Yes, it is possible using this snippet:

```CSS
.fancybox-is-scaling .fancybox-spaceball:before {
  display: none;
}
```

https://codepen.io/anon/pen/JpNmew
