### ISSUE TITLE
Improvement to css

### ISSUE THREAD

**Issue by eliz82** [fancyapps/fancybox#1855]
hello, in your css you have
```
.fancybox-caption a {
	color: #fff;
	text-decoration: underline;
}
```
https://github.com/fancyapps/fancybox/blob/master/src/css/core.css#L491-L494
is ok that you put color to <a> tag, but sometimes when you library is used in something like a wordpress theme (with light background), that theme can have a dark link tag hover:
`a:hover {color:#000;} ` 
this will make the text to disappear in fancybox3 when mouse is over the picture title, because you use a dark background behind the picture.
can i suggest using 
```
.fancybox-caption a, .fancybox-caption a:hover {
	color: #fff;
	text-decoration: underline;
}
```

**Comment by fancyapps** [comment]
Hi, Thanks!

This is the snippet from upcoming v3.3 (https://codepen.io/fancyapps/pen/VyLOJX?editors=1010) -

```CSS
.fancybox-caption a, .fancybox-caption a:link, .fancybox-caption a:visited {
    color: #ccc;
    text-decoration: none;
}

.fancybox-caption a:hover {
    color: #fff;
    text-decoration: underline;
}
```
