### ISSUE TITLE
How to make caption selectable?

### ISSUE THREAD

**Issue by alan-zhang-** [fancyapps/fancybox#1859]
Hi,

We have long text for the caption. Users may need to select part of the text and copy it. But now, these  text can't be selected.

**Comment by fancyapps** [comment]
Hi,

In the current version, click events are disabled by this CSS snippet:

```CSS
.fancybox-caption-wrap {
    pointer-events: none;
}
```

So, you can override this by setting `pointer-events: all;`. 

In future releases, this might change (see https://codepen.io/fancyapps/pen/VyLOJX)
