### ISSUE TITLE
Opinionated font-family, close button styling, and insufficient padding

### ISSUE THREAD

**Issue by brendon** [fancyapps/fancybox#1963]
Hi there :) I've just been upgrading from 3.1.20 to 3.3.5 and noticed the font-family is now hard coded. I've worked around it by setting it back to `inherit`. I've also noticed that the new close button doesn't fit nicely with the padding of the container anymore (it's a bit bigger). I've fixed this also in my own styles by enlarging the padding. Lastly, the close button has a hard-coded colour so if the container has a dark background and light text, this doesn't come through in the close button. Here are my workarounds:

```css
.fancybox-container {
  font-family: inherit;
}
.fancybox-content {
  padding: 48px;
}
.fancybox-close-small {
  color: inherit;
}
```

I was wondering if you could let me know the reason for the opinionated `font-family` style?

Totally happy if you have your reasons for the CSS changes, but just wanted to let you know in case you weren't aware of the side effects.

Have a great day! :D
