### ISSUE TITLE
Side modal without UI locked with fancybox alongside normal modals - it is possible?

### ISSUE THREAD

**Issue by 7iomka** [fancyapps/fancybox#2026]
Hi!
I want to do something like side-modal from this example: https://codepen.io/mdbootstrap/pen/QOKZGP

Please tell me how to do this?
I want to make the exit-modal, which would appear on the right side of the screen when the user visits the page for the first time, and, as in the example above, I want the opening of the modal not to block the page scrolling so that there is no overlay.

I love your plugin, and I do not want to use and configure the template for another plugin for this purpose.
Many thanks for your hard work!

**Comment by fancyapps** [comment]
Hi,

Yes, it is possible, for example:

```JS
$("[data-fancybox]").fancybox({
  baseClass : 'side-modal',
  hideScrollbar : false
});
```

CSS:

```CSS
#modal {
  max-width: 400px;
  padding: 50px;
  box-shadow: 0 0 10px 5px rgba(50, 50, 50, 0.5)
}

.side-modal .fancybox-bg {
  display: none;
}

.side-modal .fancybox-slide--html {
    text-align: right;
}
```

Demo - https://codepen.io/anon/pen/YjgRVM

**Comment by 7iomka** [comment]
Outwardly this is what we need, thanks, but still there are the following shortcomings:
.fancybox-container is located on top of all site content and blocks access to it. When a user clicks anywhere except the content of the modal directly, the modal close first, and then something else. This contradicts the idea that the side-modal on the right should appear and do not block anything on the page (not only scrolls)
Thanks for ideas!

**Comment by fancyapps** [comment]
Well, you did not mention that in your original post and your example blocks access to the page, too.

The only solution would be to resize container to match content dimensions, for example:

```CSS
.side-modal {
  max-width: 400px;  
  left: auto;
  right: 0;
}
```
or you could try to automate that:

```JS
beforeShow: function(instance, current) {
    instance.$refs.container.width( 
      $(current.src).outerWidth() /* content width */
      + (current.$slide.outerWidth() - current.$slide.width()) /* spacing around content */
    );
  }
```

I have updated the demo - https://codepen.io/anon/pen/YjgRVM

(if you wish, you could do the same for y ass, too, to make page accessible above/below the modal)
