### ISSUE TITLE
unexpected inline css rule : style="display: inline-block;"

### ISSUE THREAD

**Issue by vincent3569** [fancyapps/fancybox#2081]
hi

I use fancybox on my website, and I don't want to show thumbs on small devices.
I add css rules to have this behavior
```
@media (max-width: 767px) {
	.fancybox-button--thumbs {
		display: none;
	}
	.fancybox-thumbs {
		display: none;
	}
}
```

I recently upgrade to 3.4.2 and I noticed something strange:
My css rules doesn't work anymore when I resize the window on my desktop (but it works on small devices).

After a code revue in FF, I noticed there is an in-line css rule as following and with it my css rules can't work as rules in html are prior on css rules in side css files.

```<button data-fancybox-thumbs="" class="fancybox-button fancybox-button--thumbs" title="thumbnails" style="display: inline-block;">```

is there a way to manage your rules in css file, so they can be overwrited by mine?

**Comment by fancyapps** [comment]
Hi,

This seems to work fine (using latest version):

```CSS
@media (max-width: 767px) {
	.fancybox-button--thumbs {
		display: none;
	}

	.fancybox-show-thumbs .fancybox-inner {
		right: 0;
	}

	.fancybox-show-thumbs .fancybox-thumbs, .fancybox-thumbs {
		display: none;
	}
}
```
