### ISSUE TITLE
How to add other animation effects like slide-in and slide-out?

### ISSUE THREAD

**Issue by vanduzled** [fancyapps/fancybox#2121]
Is there a way to add slide-in, slide-out or any other effects to the animationEffect option? For example, using Animation.css or Motion UI to add to the Open/close animation type possible values. 

I actually just want to get this kind of animation the from the site below. When you click on the About link at the upper right. The overlay content slides from the right and slider out from the left when clicking close.

https://siliconvalley.baunfire.com/

https://i.imgur.com/rZS6Cgi.mp4

**Comment by fancyapps** [comment]
Hi,

It is as simple as:

```CSS
.fancybox-container {
  transform: translateX(100%);
  transition: transform .3s ease-out;
}

.fancybox-container.fancybox-is-open {
  transform: translateX(0);
}

.fancybox-container.fancybox-is-closing {
  transform: translateX(-100%);
}
```

Demo - https://codepen.io/anon/pen/RqVMEX

btw, if you want to create custom animation for content only, then check out this demo - https://codepen.io/anon/pen/QJvmzd
