### ISSUE TITLE
The "close" button and other navigation buttons are barely visible

### ISSUE THREAD

**Issue by sacredgeo** [fancyapps/fancybox#2477]
Hi. I'm using fancybox on a site I'm building. The navigation buttons are barely visible. Here's a pic:

![Screen Shot 2020-06-13 at 7 52 13 AM](https://user-images.githubusercontent.com/22250686/84568113-42050880-ad4b-11ea-878b-17895350bda8.png)

You can see the X in the top right corner. The buttons light up nicely on mouseover, but otherwise are very hard to see. I initially was just linking to the CSS and JS files. I downloaded them and linked to them within a folder of my site. I tried changing all sorts of stuff in the CSS file, such as opacity and color options. I can change the background of the button to something more visible, but the "X" remains a dark grey color.

Does anyone know how to fix this? Thank you.

**Comment by fancyapps** [comment]
Hi,

A live demo would help to give a proper answer.  Sorry, but I have no idea what could cause this issue.

**Comment by sacredgeo** [comment]
Sure, here's the website. https://www.gilgocase.com/resources.html

Click one of the youtube icons towards the bottom of the page. I would appreciate you taking a look. I should warn you, the site is regarding an unsolved criminal case and the subject matter is depressing.

**Comment by sacredgeo** [comment]
Why was this thread closed?

**Comment by fancyapps** [comment]
I was 99,99% sure that your issue was caused by your CSS on your page, and, after inspecting your page, I found this:

```CSS
input[type="submit"], input[type="reset"], input[type="button"], button, .button {
    background-color: transparent;
    color: #212931 !important; 
}
```

That means, you have made buttons (almost) invisible by yourself :) So, either remove/tweak that piece of code or owerwrite with smth like:

```CSS
.fancybox-button, .fancybox-button:link, .fancybox-button:visited {
    color: #fff !important;
}
```
