### ISSUE TITLE
Caption font size

### ISSUE THREAD

**Issue by stathimexas** [fancyapps/fancybox#2635]
How do I change font size etc in the slideshow captions?

**Comment by fancyapps** [comment]
Hi,

Sorry, I do not understand your question, how are captions related to slideshow?

If you want to change caption font size, then use CSS, for example (for v4):

```css
.fancybox__caption {
  font-size: 1.3rem;
}
```
