### ISSUE TITLE
Title helper slightly misplaced when position='top'

### ISSUE THREAD

**Issue by Fab1en** [fancyapps/fancybox#540]
I use the title helper with the following parameters : 

``` javascript
{ title : { type : 'inside', position: 'top' } };
```

This works great, but the title is slightly misplaced due to the following CSS rule :

``` CSS
.fancybox-title-inside-wrap {
    padding-top: 10px;
}
```

When the title is placed at the top, it should be 

``` CSS
.fancybox-title-inside-wrap {
    padding-bottom: 10px;
}
```

Also, this **very useful** option (position=top) should be documented somewhere. I found it by browsing the code to try to implement it.
