### ISSUE TITLE
[feat] mouse cursor over .fancybox-overlay

### ISSUE THREAD

**Issue by szepeviktor** [fancyapps/fancyBox#785]
like here:
http://www.atlantischild.hu/trening-csoport/vezetoi/ (click on a small thumbnail)

``` CSS
.fancybox-wrap {
  cursor: auto;
}
.fancybox-overlay {
  cursor: url('data:image/x-icon;base64,AAA......'), zoom-out;
}
```

or url(fancybox-close-cursor.cur)

IE needs absolute path!
