### ISSUE TITLE
Background shifts to the right

### ISSUE THREAD

**Issue by Webdinge** [fancyapps/fancyBox#879]
When you open Fancybox the background shifts to the right again. In 2.1.4 you could fix this with

.fancybox-lock{
  overflow:visible !important;
  margin-right:0px !important;
}
.fancybox-lock .fancybox-overlay {
  overflow-y: inherit!important;
}

But that doesn't help in this version.

**Comment by ttyiav** [comment]
I encountered this issue with fancybox 2.1.5 and background image on BODY with background-attachment set to **fixed** (body { background-attachment: fixed; background-image:... }).

Solved it with adding:
```CSS
html.fancybox-margin.fancybox-lock body {
    background-attachment: scroll;
}
```
While Fancybox is on screen and locks the scrolling, the rule resets attachment back to its default state. It does not have any issues, because you can not scroll.
